# Please read: https://developer.dji.com/doc/payload-sdk-api-reference/en/module/flight-controller.html#8 before use

# Horizontal control mode
uint8 DJI_FLIGHT_CONTROLLER_HORIZONTAL_ANGLE_CONTROL_MODE = 0
uint8 DJI_FLIGHT_CONTROLLER_HORIZONTAL_VELOCITY_CONTROL_MODE = 1
uint8 DJI_FLIGHT_CONTROLLER_HORIZONTAL_POSITION_CONTROL_MODE = 2
uint8 DJI_FLIGHT_CONTROLLER_HORIZONTAL_ANGULAR_RATE_CONTROL_MODE = 3

# Vertical control mode
uint8 DJI_FLIGHT_CONTROLLER_VERTICAL_VELOCITY_CONTROL_MODE = 0
uint8 DJI_FLIGHT_CONTROLLER_VERTICAL_POSITION_CONTROL_MODE = 1
uint8 DJI_FLIGHT_CONTROLLER_VERTICAL_THRUST_CONTROL_MODE = 2

# Yaw control mode
uint8 DJI_FLIGHT_CONTROLLER_YAW_ANGLE_CONTROL_MODE = 0
uint8 DJI_FLIGHT_CONTROLLER_YAW_ANGLE_RATE_CONTROL_MODE = 1

# Horizontal coordinate
uint8 DJI_FLIGHT_CONTROLLER_HORIZONTAL_GROUND_COORDINATE = 0
uint8 DJI_FLIGHT_CONTROLLER_HORIZONTAL_BODY_COORDINATE = 1

# Stable control mode
uint8 DJI_FLIGHT_CONTROLLER_STABLE_CONTROL_MODE_DISABLE = 0
uint8 DJI_FLIGHT_CONTROLLER_STABLE_CONTROL_MODE_ENABLE = 1

uint8 horizontal_control_mode
uint8 vertical_control_mode
uint8 yaw_control_mode
uint8 horizontal_coordinate
uint8 stable_control_mode
---
bool is_success